# HW0 - solution

## 2. Self-assessment

ECE 447 is a senior-level course with multiple prerequisites including EE 235 (signals and systems) and MATH 308 (linear algebra), both of which have their own prerequisites -- notably, CSE 142 (programming) and MATH 126 (multivariable calculus).  This course will draw heavily on the knowledge you acquired in these prerequisite courses; we will not cover background material in lecture.  

The following questions will help you refresh your background knowledge from prerequisite courses.  You may need to consult textbooks, websites, or other resources to answer the questions; suggested resources are indicated for each block of questions.



### 2.1 Calculus

Textbooks:  [Calculus](https://ocw.mit.edu/courses/res-18-001-calculus-fall-2023/) (MIT OpenCourseWare) by Strang; [Real mathematical analysis](http://link.springer.com/book/10.1007%2F978-3-319-17771-7) by Pugh.

a. Consider the polynomial expression $a x^2 + b x + c$.

***Note:*** this expression can be regarded as a quadratic (i.e. degree 2) polynomial in the variable $x$ or an affine (i.e. degree 1) polynomial in the variable $a$.

a.1 Regarding the expression as a polynomial in $x$, what are the roots?

---

**Solution:** If $x$ is the variable, this is a univariate quadratic equation and the roots are:\
$x = \frac{-b\pm\sqrt{b^2-4ac}}{2a}$.

Ref: https://en.wikipedia.org/wiki/Quadratic_function See 'Roots of the univariate function'.

---

a.2 Regarding the expression as a polynomial in $a$, what are the roots?

---

**Solution:** If $a$ is the variable, this is a univariate linear equation and the roots are:\
$a x^2 + b x + c=0$
 
$\Leftrightarrow x^2 a=-(bx+c)$

$\Leftrightarrow a=-\frac{bx+c}{x^2}$

---

a.3 Are any extra assumptions required for your answers to (a.1) or (a.2) to make sense?

---

**Solution:** The denominators should be non-zero numbers.

(a.1): $2a\neq0\Leftrightarrow a\neq0$. If $a=0$ then the equation becomes $bx+c=0$ and the root is $x=-\frac{c}{b}$.\
And in order to ensure the solution to be real numbers, 
$b^2-4ac\geq0$.

(a.2): $x^2\neq0\Leftrightarrow x\neq0$.

---

b. Consider the complex number $z = r e^{\theta j}\in\mathbb{C}$, where $r,\theta\in\mathbb{R}$.

b.1 What angle does $z$ make with the real axis?

---

**Solution:** 

Because $z = r e^{\theta j}$ is a polar coordinate representation of the complex number $z$, we see by inspection that $z$ makes an angle $\theta$ with the positive real axis.

b.2 When $r = 1, \theta = \pi/2$, what does $z$ equal?

---

**Solution:** 

$z|_{r = 1, \theta = \pi/2}=rcos\theta+jrsin\theta|_{r = 1, \theta = \pi/2}=j$

---

b.3 If we regard $z = r e^{\theta j}$ as a vector in the two-dimensional Cartesian plane $\mathbb{R}^2$, what are the $x$- and $y$-coordinates of $z$? (use $r$ and $\theta$ in your expression)

---

**Solution:** $x=rcos\theta$, $y=rsin\theta$

Ref: https://en.wikipedia.org/wiki/Complex_plane

---

c. Consider the functions $f : X \rightarrow Y$, $g : Y \rightarrow Z$.

***Note:*** if you are unfamiliar with this notation, it is a compact way to say "$f$ is a rule that assigns a unique value $f(x)$ in the set $Y$ to each element $x$ in the set $X$".  You may be more familiar with the notation $y = f(x)$ where $x\in X$ (that is, $x$ is an element of the set $X$) and $y\in Y$ (that is, $y$ is an element of the set $Y$).  The set $X$ is called the ***domain of $f$***.

c.1 With $h : X \rightarrow Z$ defined by $h(x) = g(f(x))$, and supposing $f$ and $g$ are continuously differentiable, provide an expression for $\frac{d}{dx} h(x)$ that is valid for all $x\in X$.

---

**Solution:** According to chain rule:\
$\frac{d}{dx} h(x) = \frac{d}{dx}g(f(x))\frac{d}{dx}f(x)$\
Ref: https://en.wikipedia.org/wiki/Chain_rule

---

c.2 Assuming $f$ is two times continuously differentiable at $x_0$, give the general expression for the second-order Taylor series of $f$ at $x_0$; your expression should have three terms in it corresponding to the function value, the value of its derivative, and the value of its second derivative.

---

**Solution:** According to Taylor series:\
$f(x)\approx f(x_0) + \frac{f'(x_0)}{1!}(x-x_0) + \frac{f''(x_0)}{2!}(x-x_0)^2$\
where $f'$ and $f''$ denote the first and second order derivative of $f(x)$.\
Ref: https://en.wikipedia.org/wiki/Taylor_series

---

c.3 With $f(x) = \sin x$, compute the first-order Taylor series of $f$ about $x_0 =\pi$, i.e. only include the first two terms from your expression in (c.2).

---

**Solution:** Based on c.2, the first-order Taylor series of $f$ is\
$f(x)\approx f(x_0) + \frac{f'(x_0)}{1!}(x-x_0)$\
plug in $f(x) = \sin x$ and $x_0 = \pi$,\
$f(x)\approx sin\pi + \frac{cos\pi}{1!}(x-\pi)$\
\$\Leftrightarrow f(x)\approx \pi - x$

---


### 2.2 signals and systems

Textbooks:  [Systems, Signals, and Transforms](https://orbiscascade-washington.primo.exlibrisgroup.com/discovery/fulldisplay?vid=01ALLIANCE_UW:UW&docid=alma99323709746301451&context=L&lang=en) by Phillips, Parr, and Riskin; [Signals and Systems](https://orbiscascade-washington.primo.exlibrisgroup.com/discovery/fulldisplay?vid=01ALLIANCE_UW:UW&docid=alma99142471020001451&context=L&lang=en) by Oppenheim, Willsky, and Hamid.

In the following problems, let 
$S$ be a single-input/single-output (SISO) linear time-invariant (LTI) system with time-domain ***impulse response*** $h:\mathbb{R}\rightarrow\mathbb{R}$,
let
$u:\mathbb{R}\rightarrow\mathbb{R}$ be a time-domain ***input*** to the system,
and let
$y:\mathbb{R}\rightarrow\mathbb{R}$ be the time-domain ***output*** corresponding to input $u$.

a. Give a time-domain expression for $y$, that is, write $y(t)$ in terms of $h$ and $u$; be explicit about any notation you introduce.

---

**Solution:** In time-domain, the system can be expressed as\
$y(t)=u(t)\otimes h(t) = \int_{-\infty}^\infty u(\tau)h(t-\tau) d\tau, \tau\in t$\
where '$\otimes$' means convolution.

---

$y(t) = (h \otimes x)(t) = \int_{-\infty}^{\infty} h(t-\tau)x(\tau)d\tau$ where $\otimes$ is the convolution operator given implicitely by the RHS.

Let 
$H = \mathcal{F}h$, 
$Y = \mathcal{F}y$, 
$U = \mathcal{F}u$
denote the Fourier transforms of the time-domain impulse response, input, and output, respectively.

b. Give a frequency-domain expression for $Y(j\omega)$, that is, write $Y(j\omega)$ in terms of $H(j\omega)$ and $U(j\omega)$.

---

**Solution:** In time-domain, the system can be expressed as\
$Y(j\omega) = H(j\omega)U(j\omega)$

***Notice:***  your expression for $y(t)$ in (a.) depends on the value of $h$ and $u$ at ***all times*** (not just the time $t$), whereas your expression for $Y(j\omega)$ in (b.) depends only on the value of $H$ and $U$ at frequency $\omega$.
This illustrates the key strength of frequency-domain analysis -- convolution in the time domain turns into multiplication in the frequency domain.

---

c. Give the general expression for the Fourier transformation $\mathcal{F}$, that is, write $H(j\omega)$ in terms of $h$.

---

**Solution:** \
$H(j\omega) = \int_{-\infty}^{\infty} h(t) e^{-j\omega t} dt$
Ref: https://en.wikipedia.org/wiki/Fourier_transform

---

d. Give the general expression for the ***inverse*** Fourier transformation $\mathcal{F}^{-1}$, that is, write $h(t)$ in terms of $H$.

---

**Solution:** According to inverse Fourier transform,

$h(t) = \int_{-\infty}^{\infty} H(j\omega)e^{j\omega t} d\omega$

***Notice:*** since an integral is an infinite sum, you can infer from the expressions in (c.) and (d.) that 
the time-domain signal $h$ can be represented as an infinite linear combination of frequency-domain exponentials,
and similarly that 
the frequency-domain signal $H$ can be represented as an infinite linear combination of time-domain exponentials.

### 2.3 linear algebra 

Textbooks:  [Introduction to Applied Linear Algebra](http://vmls-book.stanford.edu/) by Boyd and Vandenberghe; [Linear Algebra](http://joshua.smcvt.edu/linearalgebra/) by Hefferon.

In the following problems, let 
$A = \left[\begin{array}{} A_{11} & A_{12} \\ 0 & A_{22} \end{array}\right]\in\mathbb{R}^{2\times 2}$ 
be a matrix with ***shape*** $2\times 2$,
$B = \left[\begin{array}{} B_{11} \\ B_{21} \end{array}\right]\in\mathbb{R}^{2\times 1}$
be a matrix with shape $2\times 1$,
and
$x = \left[\begin{array}{} x_{1} \\ x_{2} \end{array}\right]\in\mathbb{R}^{2}$
be a vector with ***length*** $2$. 

a. Determine the eigenvalues of $A$.

---
**SOLUTION**
If $\lambda$ is an eigenvalue of $A$, and $x \neq 0$ is the corresponding eigenvector, then $(\lambda, x)$ must satisfy

$$ (A-\lambda I)x = 0 $$

since $x \neq 0$, the equation above only has a solution if the determinant $|A-\lambda I| = 0$. Therefore, the eigenvalues are roots of the *characteristic polynomial*

$$ (A_{11}-\lambda)(A_{22}-\lambda) = 0$$

for which there are clearly two solutions $\lambda_1, \, \lambda_2$

$$ \fbox{ $ \lambda_1 = A_{11}, \, \lambda_2 = A_{22}$ }$$

---

b. Compute the determinant of $A$.

---
**SOLUTION**
The general formula for the determinant of a $2 \times 2$ matrix $A$ is 

$$ |A| = A_{11} A_{22} - A_{12}A_{21}$$

where $A_{ij}$ is the entry of $A$ in row $i$ and column $j$. So, if $A_{21}=0$, we have

$$ |A| = A_{11} A_{22} $$

---

c. Compute $Ax$ and $x^\top A^\top$ using matrix multiplication, where $M^\top$ denotes the ***transpose*** of matrix $M$.

---
**SOLUTION**

Given two matrices (or vectors) with compatible dimension $A \in \mathbb{R}^{n,m}$ and $B \in \mathbb{R}^{m,p}$ the general formula for matrix multiplication $AB$ is 

$$ (AB)_{ij} = \sum_{k=1}^m A_{ik}B_{kj}$$

Hence if  $y = Ax$ then the entries of $y$ are given by 

$$ 
y = \left[ \begin{array}{c} A_{11}x_1 + A_{12}x_2 \\ A_{22}x_2\end{array}\right]
$$

---

d. Why can't you compute $x A$ or $A^\top x^\top$ using matrix multiplication?

---
**Solution**

The usual rules for matrix multiplication require that the *inner dimension* of the operands agree. In other words, to calculate $AB$, we require that the number of columns in $A$ equals the number of rows in $B$. If $x$ is a vector in $\mathbb{R}^n$, then we treat $x$ as an $(n \times 1)$ matrix for the purpose of calculating $Ax$.

In this way, $Ax^\top$ does not make sense, because we would be trying to multiply a $(n \times n)$ matrix by a $(1 \times n)$ matrix, whose inner dimensions do not agree. Theoretically, $x^\top$ is not a vector but it is a *dual vector*, and hence $x^\top$ is not in the domain of left-multiplication by $A$.

The exact same argument can be made used to show that $xA$ is not meaningful. Practically speaking, their inner dimensions do not agree. Theoretically , right-multiplication by a $A$ is a linear map between *dual vector spaces*, but $x$ is a vector, and so is not in the domain of right-multiplication by $A$.

---

e. Compute $B + x$; is the result a matrix or vector?

---
**Solution**
While it possible to *define* a kind of addition to calculate $x+B$, you should pause first. Why? Because $B$ is a matrix, while $x$ is a vector, and addition between matrices and vectors of any shape is not defined. Should $B+x$ be a vector, or a matrix? Actually, we cannot say without making an (arbitrary) choice!

To expand on this point a little further, we want to distinguish $\mathbb{R}^{n \times 1}$ from $\mathbb{R}^n$. Both are naturally vectorspaces, and each have their own addition operation,

$$ +_{n \times 1} : \mathbb{R}^{n \times 1} \times \mathbb{R}^{n \times 1} \to \mathbb{R}^{n \times 1}$$

is the addition on $\mathbb{R}^{n \times 1}$, and 

$$ +_n : \mathbb{R}^n \times \mathbb{R}^n \to \mathbb{R}^n $$

is the addition on $\mathbb{R}^n$. However, without making a choice about whether the result of $B+x$ is a matrix or a vector, we cannot define an addition that takes an element of $\mathbb{R}^{n \times 1}$ and adds it to an element of $\mathbb{R}^n$.

*Note: in numpy, if you try to naively add a 1-column ndarray (a matrix) to an array of the same size (vector), you will probably not get the result you were expecting. *

--- 

### 2.4 scientific computing

Resources:  [NumPy for Matlab users](http://mathesaurus.sourceforge.net/matlab-numpy.html); [Dive into Python](http://www.diveintopython3.net/); [NumPy Manual](https://docs.scipy.org/doc/numpy/reference/)

a. Familiarize yourself with the JupyterHub Notebook and Programming in Python using the resources on the ***Computational Tools*** section of the Syllabus (Canvas home page).

In the following problems, let 
$A = \left[\begin{array}{} 0 & 1 \\ -10 & -1 \end{array}\right]$,
$B = \left[\begin{array}{} 0 \\ 1 \end{array}\right]$.

b. Determine the eigenvalues of $A$ using a numerical linear algebra library (`numpy.linalg.eigvals` in NumPy).

In [1]:
# code part b here
import numpy as np
A=np.array([[0,1],[-10, -1]])
print(A)
B=np.transpose(np.array([[0,1]]))
print(B)
C=np.linalg.eigvals(A)
print(C)
D=np.linalg.det(A)
print(D)
F=np.dot(A,B)
print(F)
H=np.dot(np.transpose(B),np.transpose(A))
print(H)
#np.dot(np.transpose(A),np.transpose(B))
#you'll get an error when you uncomment


[[  0   1]
 [-10  -1]]
[[0]
 [1]]
[-0.5+3.122499j -0.5-3.122499j]
10.000000000000002
[[ 1]
 [-1]]
[[ 1 -1]]


c. Compute the determinant of $A$  using a numerical linear algebra library (`numpy.linalg.det` in NumPy).

In [2]:
# code part c here
print(np.linalg.det(A))

10.000000000000002


d. Compute $AB$ and $B^\top A^\top$ using numerical matrix multiplication (`numpy.dot` in NumPy; ***not*** "`*`"); what are the resulting ***shapes***?

In [3]:
# code part d here
AB = np.dot(A,B)
BTAT = np.dot(B.T,A.T)
# or equivalently
AB = A@B
BTAT = B.T@A.T

# Shape of AB
print(AB.shape)
# Shape of A.T
print(BTAT.shape)

(2, 1)
(1, 2)


e. What happens (i.e. what error do you receive) when you try the following numerical matrix multiplications: $B A$ or $A^\top B^\top$?

In [4]:
# code part e here
B@A # results in ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)